Insert Into destination 
Values(9, 'Stanely bridge','Alexandria, Egypt.','What a wonderfull bridge!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(10, 'Pyramids','Giza, Egypt.','What a wonderfull pyramid!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(11, 'Luxor temple','Aswan, Egypt.','What a wonderfull temple!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(12, 'Cairo tower','Cairo, Egypt.','What a wonderfull tower!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(13, 'Abu sembel temple','Luxor, Egypt.','What a wonderfull temple!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(14, 'bahamas','Alexandria, Egypt.','What a wonderfull bahama!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(15, 'john','Benisuef, Egypt.','What a wonderfull person!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
Insert Into destination 
Values(16, 'shosho','Helwan, Egypt.','What a wonderfull girl!','https://images.unsplash.com/photo-1588773960418-d0307af4f047?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80','https://images.unsplash.com/photo-1551801841-ecad875a5142?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1936&q=80','It is the first bridge in Egypt to be constructed into the sea , with total length of 400 m. Considered of 6 spans , It constitute amajor part of the reconstruction and decoration of Alexandria cornich . A master piece of architectureal precision, the bridge preserves the architectural style of the famous and cosmopolitan Egyptian city.','Stanley Bridge is the first bridge in Egypt to be constructed over the sea, allowing natives and visitors to experience the architectural style of the cosmopolitan Egyptian city. It is considered by many to be a major part of the reconstruction and decoration of Alexandria beach.');
